apiVersion: v1
kind: Service
metadata:
  labels:
      app: backend-user-svc
  name: backend-user
  namespace: default
spec:
  selector:
    service: backend-user
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080