apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-feed