apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name:  frontend
        image: youssefamr/udagram-frontend:latest
        imagePullPolicy: Always  
        ports: 
        - containerPort: 80
      restartPolicy: Always