apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  namespace: default
  labels:
    app: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy